apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pulp-operator-manager-rolebinding
  namespace: ${ namespace }
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pulp-operator-manager-role
subjects:
- kind: ServiceAccount
  name: ${service_account}
  namespace: ${ namespace }
