# ...existing code...
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pulp-operator.fullname" . }}-leader-election-role
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulp-operator.fullname" . }}-manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - pods/log
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups
  - pulps
  verbs:
  - get
  - list
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups/finalizers
  verbs:
  - update
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulpbackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulprestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulprestores/finalizers
  verbs:
  - update
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulprestores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulps/finalizers
  verbs:
  - update
- apiGroups:
  - repo-manager.pulpproject.org
  resources:
  - pulps/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  - routes/custom-host
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulp-operator.fullname" . }}-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "pulp-operator.fullname" . }}-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pulp-operator.fullname" . }}-leader-election-rolebinding
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pulp-operator.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "pulp-operator.fullname" . }}-controller-manager
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pulp-operator.fullname" . }}-manager-rolebinding
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pulp-operator.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "pulp-operator.fullname" . }}-controller-manager
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pulp-operator.fullname" . }}-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pulp-operator.fullname" . }}-manager-role
subjects:
  - kind: ServiceAccount
    name: {{ include "pulp-operator.fullname" . }}-controller-manager
    namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "pulp-operator.fullname" . }}-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pulp-operator.fullname" . }}-proxy-role
subjects:
- kind: ServiceAccount
  name: {{ include "pulp-operator.fullname" . }}-controller-manager
  namespace: {{ .Values.namespace }}



