---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pulp-operator.fullname" . }}-controller-manager
  namespace: {{ .Values.operatorNamespace | default .Values.namespace }}
  labels:
    app: {{ template "pulp-operator.fullname" . }}
    control-plane: controller-manager
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    owner: pulp-dev
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: {{ .Chart.Name }}
    owner: pulp-dev
    {{- include "pulp-operator.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations: {{ toYaml .Values.serviceAccount.annotations | nindent 4 }}
{{- end }}
